{{- $fullName := include "storj-storagenode.fullname" . -}}
{{- $labels := include "storj-storagenode.labels" . -}}
{{- $selectorLabels := include "storj-storagenode.selectorLabels" . -}}
{{- range $name, $service := .Values.service -}}
  {{- if $service.enabled | default "true" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    {{- with $service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $service }}
  type: {{ .type }}
  {{ if .loadBalancerIP }}loadBalancerIP: {{ .loadBalancerIP }}{{ end }}
  {{ if .externalIPs }}externalIPs: {{ toYaml .externalIPs | nindent 2 }}{{ end }}
  ports:
    - port: {{ .port }}
      targetPort: {{ $name }}
      {{- if .protocol }}
      {{- if or ( eq .protocol "HTTP" ) ( eq .protocol "HTTPS" ) ( eq .protocol "TCP" ) }}
      protocol: TCP
      {{- else }}
      protocol: {{ .protocol }}
      {{- end }}
      {{- else }}
      protocol: TCP
      {{- end }}
      name: {{ $name }}
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
  {{- end }}
{{ end }}
