{{- if .Values.identity.vaultSecret }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
spec: {{ toYaml .Values.identity.vaultSecret.spec | nindent 2 }}
{{- end }}
